name: Label Test Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo label name
        run: |
            echo "Label added: ${{ github.event.label.name }}"
