name: test cli actions
on:
  pull_request:
    types:
      - labeled
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - run: |
                REPOSITORY=$(gh api graphql -f query='{repository(owner: "bhanufyi", name: "test-portfolio") {id}}' | jq -r '.data.repository.id')
                BRANCH_NAME=stage_re
                gh api graphql -f query="
                mutation {
                    createBranchProtectionRule(input: {
                        repositoryId: \"$REPOSITORY\",
                        pattern: \"$BRANCH_NAME\",
                        allowsDeletions: false,
                        allowsForcePushes: false,
                        isAdminEnforced: true,
                        requiresLinearHistory: true,
                    }) {
                        clientMutationId
                    }
                }"
            env:
              GITHUB_TOKEN: ${{ secrets.PAT }}

